### ISSUE TITLE
September meeting follow-up (post links and your details here!)

### ISSUE THREAD

**Issue by gyaresu** [nodeschool/vancouver#56]
Hi folks! Just a starting a thread to kick off the follow-up from meeting all you lovely humans.

Post all your relevant links and contact info! 

### Suggested reading/watching:
 - [Fun Fun Function (best JS tutorials on YouTube)](https://www.youtube.com/channel/UCO1cgjhGzsSYb1rsB4bFe4Q)
 - [Mozilla Developer Network (Javascript documentation) ](https://developer.mozilla.org/en-US/docs/Web/JavaScript)
 - [Nodejs Documentation](https://nodejs.org/api/)
 - [Johnny-five Javascript robotics platform](http://johnny-five.io/)
   - [Nodebots workshop](https://github.com/tableflip/nodebot-workshop)
 - [DuckDuckGo (DDG) is a great search engine](https://duckduckgo.com)
   - Search directly from the source in DDG with [Bang](https://duckduckgo.com/bang) syntax. i.e. `!js String.replace`

![bitmoji](https://render.bitstrips.com/v2/cpanel/9945775-322108779_2-s4-v1.png?transparent=1&palette=1&width=246)

### _"Hire Gareth!"_
_(I'm looking for a job but need to be a contractor for 3 months until I get my Open Work Permit)_ 

Twitter: [gareth__](https://twitter.com/gareth__)
LinkedIn: [garethcodes](https://www.linkedin.com/in/garethcodes/)

**Comment by lexi933** [comment]
Hi All,
Thanks so much for putting on today's session, the pizza, the connections and help! 

Here's the meetup I was mentioning: [Microservices Design and Implementation using DDD, CQRS and Event Sourcing](https://www.meetup.com/DDD-CQRS-ES/)
* We'll be supporting our friends from the other [Microservices Meetup](https://www.meetup.com/Vancouver-Microservices-Meetup/) on Sep 21st and will be at Hootsuite instead of our usual venue.

We usually live stream via [@AdvTechPodcast](https://twitter.com/AdvTechPodcast)

Latest podcast episode was on [cryptocurrency](https://advancetechmedia.org/episode-005-erik-reppel-robert-reppel/) and next up will be Brian Benz, Senior Developer Advocate promoting open source initiatives over at Microsoft.  We're on iTunes and Google play as well just search for Advance Tech Podcast.

A few other relevant links and ways to reach me:
* I'm Director of Business Development at [Adaptech Solutions](https://adaptechsolutions.net/)
* We have a few open source projects you can check out on our [github account](https://github.com/adaptech) (nota is a great place to start)
* You can check out my [learning to code blog](https://medium.com/p/5a4555fcc54/edit) and [github](https://github.com/lexi933)
* I'm a big fan of community development and mentoring - happy to give shoutouts via social media and cross-promote projects and other things you're working on! Best channels are [twitter](https://twitter.com/Alexandra933) and [LinkedIn](https://www.linkedin.com/in/alexandra-moxin/)

**Comment by ruxandrafed** [comment]
Nice to meet everyone today! Thanks for coming 😄 

Twitter: https://twitter.com/ruxandrafed
LinkedIn: https://www.linkedin.com/in/ruxandrafediuc/
Telus Digital website: https://labs.telus.com
Women Who Code YVR Meetup Group: https://www.meetup.com/Women-Who-Code-Vancouver/

See you around! 👋

**Comment by AzzaRojbi** [comment]
It was nice meeting everyone on Saturday 😄 
Here is the link to the Shia LaBeouf chrome extension haha! https://chrome.google.com/webstore/detail/do-it/eppncnmppghbndacgkideegigaminkfg?hl=en

Twitter: https://twitter.com/azzarojbi
LinkedIn: https://www.linkedin.com/in/azza-rojbi/

**Comment by AzzaRojbi** [comment]
Hey @gyaresu I noticed your twitter and LinkedIn links seems to be broken

**Comment by keywordnew** [comment]
Closing this as its purpose has been served
