### ISSUE TITLE
Update our chapter JSON file

### ISSUE THREAD

**Issue by lvivier** [nodeschool/vancouver#8]
Part of setting up a NodeSchool chapter is creating a chapter.json file and submitting it to the NodeSchool website repo. We should update ours:
- [chapter.json docs](https://github.com/nodeschool/organizers#5)
- [nodeschool/nodeschool.github.io/chapters/vancouver.json](https://github.com/nodeschool/nodeschool.github.io/blob/source/chapters/vancouver.json)

**Comment by gyaresu** [comment]
Hmm. Twitter account seems a little too-much overhead.
- Account password
- Tweets are UDP not TCP (No-one's notified by them, they just pass by in a stream)
- We'll only use it when there's an event

Gitter: mmmm, yes kinda.

Although I'm going to go a little Stallman here and point out that it's not FLOSS and in principle I'm against that. So I'd like to see an alternative.

http://blog.gitter.im/2015/03/31/free-for-teams-of-up-to-25/
https://gitter.workable.com/jobs/43162

Thoughts?

**Comment by bmann** [comment]
I guess @sintaxi runs the NodeBrigade Twitter account, but uses it rarely. I don't think we need to do anything there for the moment. Let's just use NodeBrigade as the "official" account, but use #nodeschoolvan as the hashtag to coalesce around.

I think Gitter is fine for chat, especially live for the events.

If you want to run a "room" in the WeAReYVR / PixelCrafters Slack channel, feel free to do that http://chat.weareyvr.ca

In reality? I probably don't need more places for real time chat. All depends on what actually gets used. Would love to use issues here and PRs on the website for now, and leave other tools up for whatever happens to work over time.

Sounds like Tito is it for events. Do we have a NodeSchool Vancouver "organization" there? It has an embed code which we could stick in place of the Meetup stuff that's on the front page now.

@gyaresu I used to be more Stallman, I'm pretty pragmatic these days.

**Comment by gyaresu** [comment]
## Comms platform

@bmann I am also. With things like Facebook/Meetup/Slack it's just often better to expect the best and prepare for the worst.
10K post history in Slack has bitten http://www.freecodecamp.com/ for example because they've now accumulated over 3K users in.... about 5mins (it feels like). I did mention this to Quincey at the time he moved from Gitter but Slack is a really great UX, so I _get_ it.

Anyhow, yes. Gitter for now. Until someone drags Freenode from the 90's.

And yes to the fracturing of communications. I barely know where to search for past conversations any more. "I know someone mentioned that somewhere..."

## ti.to

https://ti.to/docs/widget

Which would be:

```
<!-- place this in your head tag -->
<script src='https://js.tito.io/v1' async></script>

<!-- Place this where you want the widget to appear -->
<tito-widget event="nodeschool-vancouver/2015-05-23"></tito-widget>
```

But I just fired that code up in a default Jekyll page and it looks like this:

![screenshot 2015-05-24 17 44 44](https://cloud.githubusercontent.com/assets/29263/7790437/a6a47cb8-023c-11e5-8197-71b8ff86d807.png)

Not like the styling in the api docs

![screenshot 2015-05-24 17 45 33](https://cloud.githubusercontent.com/assets/29263/7790444/be874856-023c-11e5-875e-226a8546c0ec.png)

**Comment by bmann** [comment]
The event is over. There is a different "list of all events for this organization" embed. I haven't looked at it in a while.

**Comment by lvivier** [comment]
@bmann there's a nodeschool-vancouver org on Tito, I added you so you can check it out :+1:

**Comment by lvivier** [comment]
ref https://github.com/nodeschool/nodeschool.github.io/pull/381
